language: node_js
sudo: false
node_js:
- '4.2'
before_install:
- npm install -g grunt-cli
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: cbKlb8DOVjiEqrauh8b9iCjW1txizd2D8fPEOf0tuevlmijil28sP6bkddcCmdqUP5uI9PimoTTUC1cBH1aWk7MTXzqcDNeO5ty1YkN188L0mXmbz+gMtGIm6MRrYWVzAWdmMUlDjpLZGxCFMm/pGPwdt29FFOCwvH7VdINFNzY=
  on:
    tags: true
    repo: the-grid/html-flatten
